### ISSUE TITLE
部署合约Connection reset

### ISSUE THREAD

**Issue by lengmianshi** [WeBankBlockchain/WeBASE-Node-Manager#521]
写了一个测试的合约：
![image](https://github.com/user-attachments/assets/ff43254d-6cb9-4da4-81c9-b7322b7adbec)

部署时webase-node-manager报错：
![image](https://github.com/user-attachments/assets/a47e0677-045b-4633-81d0-55582e896e72)

其中webase-front服务没有异常

**Comment by lengmianshi** [comment]
sign服务异常：

> 024-08-09 16:54:31.425 [http-nio-5002-exec-7] INFO  TransService() - transactionDataHash after:0x6c162bc7d8c80524c0b43057022f1400f0c841c877596674602197ad7b62ec1a
2024-08-09T08:54:31.800035700Z 2024-08-09 16:54:31.426 [http-nio-5002-exec-7] INFO  KeyStoreService() - getSignData url:http://192.168.50.2:5004/WeBASE-Sign/sign/hash
2024-08-09T08:54:31.800040900Z 2024-08-09 16:54:31.436 [http-nio-5002-exec-7] ERROR ExceptionsHandler() - catch bindExceptionHandler:[]
2024-08-09T08:54:31.800044300Z org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{"timestamp":"2024-08-09T08:54:31.433+00:00","status":404,"error":"Not Found","path":"/WeBASE-Sign/sign/hash"}"
2024-08-09T08:54:31.800048200Z 	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800051600Z 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800056500Z 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800059900Z 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800063100Z 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800066100Z 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800069000Z 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800072000Z 	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:443) ~[spring-web-5.3.26.jar:5.3.26]
2024-08-09T08:54:31.800074900Z 	at com.webank.webase.front.keystore.KeyStoreService.getSignData(KeyStoreService.java:281) ~[WeBASE-Front-3.1.0.jar:?]
2024-08-09T08:54:31.800077800Z 	at com.webank.webase.front.transaction.TransService.requestSignHashFromSign(TransService.java:702) ~[WeBASE-Front-3.1.0.jar:?]

**Comment by lengmianshi** [comment]
版本信息：
webase-sign: 3.1.1
webase-front：3.1.1
webase-node-manager：3.1.1
webase-web：3.1.1

**Comment by CodingCattwo** [comment]
检查一下从webase-node-mgr到webase-front到网络是否连通，检查front服务是否已停止。
